"""README rendering logic extracted from render_status.py.

Handles:
- Project root README.md generation
- prompts/landing/README.md generation with LP-sequence preservation

This module is imported by render_status.py. It is NOT a standalone script.
"""
from __future__ import annotations

import hashlib
import os
import re

import _yaml_compat as yaml


def _build_dependency_graph_text(status: dict) -> str:
    arts = status.get("artifacts") or []
    lines = []
    for a in arts:
        for dep in a.get("depends_on") or []:
            lines.append(f"{dep} <- {a['id']}")
    if not lines:
        return "(无依赖关系)"
    return "\n".join(lines)


def _topological_sort_lps(artifacts: list) -> list:
    lps = [a for a in artifacts if a.get("type") == "landing_prompt"]
    if not lps:
        return []
    ids = {a["id"] for a in lps}
    graph = {a["id"]: [] for a in lps}
    in_degree = {a["id"]: 0 for a in lps}
    for a in lps:
        for dep in a.get("depends_on") or []:
            if dep in ids:
                graph[dep].append(a["id"])
                in_degree[a["id"]] += 1
    queue = sorted([n for n, d in in_degree.items() if d == 0])
    result = []
    while queue:
        node = queue.pop(0)
        result.append(node)
        for neighbor in sorted(graph.get(node, [])):
            in_degree[neighbor] -= 1
            if in_degree[neighbor] == 0:
                queue.append(neighbor)
    if len(result) < len(lps):
        remaining = sorted(ids - set(result))
        result.extend(remaining)

    # B5 fix: map IDs to filename stems for more precise sequence tokens.
    # ELP's LP 序列解析 uses substring matching against these tokens.
    id_to_stem = {}
    for a in lps:
        path = a.get("path", "")
        if path:
            stem = os.path.splitext(os.path.basename(path))[0]
            id_to_stem[a["id"]] = stem
        else:
            id_to_stem[a["id"]] = a["id"]
    return [id_to_stem.get(aid, aid) for aid in result]


def render_project_readme(status: dict, project: str) -> str:
    meta = status.get("meta") or {}
    proj = status.get("project") or {}
    proj_name = proj.get("name") or meta.get("project_name", "Unknown Project")
    arts = status.get("artifacts") or []
    findings = status.get("research_findings") or []
    decisions = status.get("decisions") or []
    hcs = status.get("handoff_contexts") or []
    blockers = status.get("blockers") or []

    lines = []
    lines.append(f"# {proj_name} — Project State Overview")
    lines.append("")
    lines.append("> Auto-generated by project-state-tracker. Do not hand-edit.")
    lines.append(f"> Last updated: {meta.get('last_run', 'unknown')}")
    lines.append("")

    lines.append("## 目录结构")
    lines.append("")
    dir_counts = {}
    for subdir in ["research", "decisions", "plan", os.path.join("prompts", "landing"),
                   os.path.join("prompts", "test"), "status", "views", "tools"]:
        full = os.path.join(project, subdir)
        if os.path.isdir(full):
            count = sum(1 for f in os.listdir(full)
                       if os.path.isfile(os.path.join(full, f)) and f not in (".gitkeep", ".gitignore"))
            dir_counts[subdir] = count
    for d, desc in [("research", "调研事实与证据"), ("decisions", "基于调研的决策"),
                    ("plan", "执行计划与设计"), (os.path.join("prompts", "landing"), "实施 Prompt"),
                    (os.path.join("prompts", "test"), "验证 Prompt")]:
        if d in dir_counts:
            lines.append(f"{d.ljust(20)}— {desc} ({dir_counts[d]} files)")
    lines.append("status/status.yaml  — 状态单一真相源")
    if "views" in dir_counts:
        lines.append("views/              — 只读派生视图")
    if "tools" in dir_counts:
        lines.append("tools/              — Python 状态管理脚本")
    lines.append("")

    all_arts = []
    for rf in findings:
        all_arts.append((rf.get("id", "?"), "research", rf.get("status", "?"), rf.get("path", "")))
    for d in decisions:
        all_arts.append((d.get("id", "?"), "decision", d.get("status", "?"), d.get("path", "")))
    for a in arts:
        all_arts.append((a.get("id", "?"), a.get("type", "?"), a.get("status", "?"), a.get("path", "")))
    all_arts.sort(key=lambda x: x[0])

    lines.append("## Artifact 状态总览")
    lines.append("")
    if all_arts:
        lines.append("| ID | Type | Status | Path |")
        lines.append("|----|------|--------|------|")
        for aid, atype, astatus, apath in all_arts:
            lines.append(f"| {aid} | {atype} | {astatus} | {apath} |")
    else:
        lines.append("无已注册 artifact")
    lines.append("")

    lines.append("## 依赖关系图")
    lines.append("")
    lines.append(_build_dependency_graph_text(status))
    lines.append("")

    lines.append("## Handoff 上下文")
    lines.append("")
    if hcs:
        lines.append("| HC | Producer | Status | Version | Consumers |")
        lines.append("|----|----------|--------|---------|-----------|")
        for hc in hcs:
            consumers = ", ".join(hc.get("consumed_by") or []) or "(none)"
            lines.append(f"| {hc.get('id')} | {hc.get('producer', '?')} | {hc.get('status', '?')} | {hc.get('version', '?')} | {consumers} |")
    else:
        lines.append("(无活跃 handoff)")
    lines.append("")

    lines.append("## Blockers")
    lines.append("")
    open_blockers = [b for b in blockers if b.get("status") == "open"]
    if open_blockers:
        for b in open_blockers:
            lines.append(f"- **{b.get('id')}** ({b.get('severity', '?')}): {b.get('title', '')}")
    else:
        lines.append("(无阻塞项)")
    lines.append("")

    lines.append("## 快速导航")
    lines.append("")
    lines.append("- 完整状态数据: status/status.yaml")
    lines.append("- 变更日志: views/change_impact_report.md")
    lines.append("- Prompt 执行链: views/prompt_chain_view.md")
    lines.append("- Handoff 详情: views/handoff_view.md")
    lines.append("")
    return "\n".join(lines)


def render_landing_readme(status: dict, project: str) -> str:
    meta = status.get("meta") or {}
    proj = status.get("project") or {}
    proj_name = proj.get("name") or meta.get("project_name", "Unknown Project")
    arts = status.get("artifacts") or []
    hcs = status.get("handoff_contexts") or []

    source_root = meta.get("source_root", "<未配置>")
    scope = meta.get("scope") or []
    pst_root_val = meta.get("pst_root", "<未配置>")

    fm_lines = ["---"]
    fm_lines.append(f'source_root: "{source_root}"')
    if scope:
        fm_lines.append("scope:")
        for s in scope:
            fm_lines.append(f'  - "{s}"')
    if pst_root_val and "未配置" not in pst_root_val:
        fm_lines.append(f'pst_root: "{pst_root_val}"')
    fm_lines.append("---")
    new_frontmatter = "\n".join(fm_lines)

    body_lines = []
    body_lines.append(f"# {proj_name} LandingPrompt")
    body_lines.append("")
    body_lines.append("> Auto-generated body by project-state-tracker. Front-matter and LP 序列 preserved if pre-existing.")
    body_lines.append(f"> Last updated: {meta.get('last_run', 'unknown')}")
    body_lines.append("")

    lp_order = _topological_sort_lps(arts)
    body_lines.append("## LP 序列")
    body_lines.append("")
    if lp_order:
        body_lines.append(" -> ".join(lp_order))
    else:
        body_lines.append("尚无已注册的 Landing Prompt")
    body_lines.append("")

    coding_standards = meta.get("coding_standards")
    if coding_standards:
        body_lines.append("## Coding Standards")
        body_lines.append("")
        body_lines.append(coding_standards)
        body_lines.append("")

    lps = [a for a in arts if a.get("type") == "landing_prompt"]
    body_lines.append("## 当前 LP 状态")
    body_lines.append("")
    if lps:
        body_lines.append("| ID | Status | Depends On | Produces HC |")
        body_lines.append("|----|--------|------------|-------------|")
        for lp in lps:
            deps = ", ".join(lp.get("depends_on") or []) or "(none)"
            produces = ", ".join(lp.get("produces_handoffs") or []) or "(none)"
            body_lines.append(f"| {lp.get('id')} | {lp.get('status', '?')} | {deps} | {produces} |")
    else:
        body_lines.append("尚无已注册的 Landing Prompt")
    body_lines.append("")

    lp_ids = {a.get("id") for a in lps}
    relevant_hcs = [hc for hc in hcs if hc.get("producer") in lp_ids or
                    any(c in lp_ids for c in (hc.get("consumed_by") or []))]
    body_lines.append("## Handoff 上下文摘要")
    body_lines.append("")
    if relevant_hcs:
        body_lines.append("| HC | Facts | Constraints | Consumed By |")
        body_lines.append("|----|-------|-------------|-------------|")
        for hc in relevant_hcs:
            facts = hc.get("facts") or []
            constraints = hc.get("constraints") or []
            fact_strs = []
            for f in facts:
                if isinstance(f, dict):
                    fact_strs.append(f.get("statement", str(f.get("id", "?"))))
                else:
                    fact_strs.append(str(f))
            constraint_strs = []
            for c in constraints:
                if isinstance(c, dict):
                    constraint_strs.append(c.get("statement", str(c.get("id", "?"))))
                else:
                    constraint_strs.append(str(c))
            facts_summary = "; ".join(fact_strs[:3]) if fact_strs else "(none)"
            constraints_summary = "; ".join(constraint_strs[:3]) if constraint_strs else "(none)"
            consumers = ", ".join(hc.get("consumed_by") or []) or "(none)"
            body_lines.append(f"| {hc.get('id')} | {facts_summary} | {constraints_summary} | {consumers} |")
    else:
        body_lines.append("(无活跃 handoff)")
    body_lines.append("")

    new_body = "\n".join(body_lines)
    return new_frontmatter + "\n\n" + new_body


def _parse_frontmatter_dict(fm_text: str) -> dict:
    out = {}
    if not fm_text:
        return out
    lines = fm_text.strip().splitlines()
    if lines and lines[0].strip() == "---":
        lines = lines[1:]
    if lines and lines[-1].strip() == "---":
        lines = lines[:-1]
    for raw in lines:
        line = raw.rstrip()
        if not line or line.lstrip().startswith("#") or ":" not in line:
            continue
        key, _, value = line.partition(":")
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        if key and value:
            out[key] = value
    return out


def _lp_sequence_body(section_text: str) -> str:
    if not section_text:
        return ""
    lines = section_text.splitlines()
    if lines and lines[0].lstrip().startswith("## "):
        lines = lines[1:]
    return "\n".join(line.rstrip() for line in lines).strip()


def write_landing_readme_with_preservation(path: str, new_content: str, status: dict, project: str = None):
    """Write landing README preserving user front-matter and user-authored LP sequence.

    Preservation rules (lp_sequence_source-driven, hash-anchored):
    1. File does not exist -> write new_content as-is.
    2. lp_sequence_source: "auto" -> regenerate unless human edited (hash mismatch flips to "user").
    3. lp_sequence_source: "user" or absent -> preserve existing LP sequence verbatim.
    4. Front-matter (other keys) always preserved from existing file.
    """
    if not os.path.isfile(path):
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w", encoding="utf-8") as f:
            f.write(new_content)
        if project:
            try:
                _maybe_seed_lp_sequence_hash(path, new_content, project)
            except Exception:
                pass
        return

    existing = ""
    with open(path, "r", encoding="utf-8") as f:
        existing = f.read()

    existing_fm = ""
    existing_body = existing
    if existing.startswith("---"):
        second_dash = existing.find("---", 3)
        if second_dash != -1:
            existing_fm = existing[:second_dash + 3]
            existing_body = existing[second_dash + 3:].lstrip("\n")

    existing_lp_section = None
    lp_pattern = re.compile(r"(## LP 序列\s*\n)(.*?)(?=\n## |\Z)", re.DOTALL)
    lp_match = lp_pattern.search(existing_body)
    if lp_match:
        existing_lp_section = lp_match.group(0).strip()

    new_fm = ""
    new_body = new_content
    if new_content.startswith("---"):
        second_dash = new_content.find("---", 3)
        if second_dash != -1:
            new_fm = new_content[:second_dash + 3]
            new_body = new_content[second_dash + 3:].lstrip("\n")

    fm_dict = _parse_frontmatter_dict(existing_fm)
    lp_source = fm_dict.get("lp_sequence_source", "user").strip().lower()

    final_fm = existing_fm if existing_fm else new_fm
    new_lp_match = lp_pattern.search(new_body)

    if existing_lp_section and new_lp_match:
        if lp_source == "auto" and project:
            cache_dir = os.path.join(project, "status", ".cache")
            hash_file = os.path.join(cache_dir, "lp_sequence_hash.txt")
            existing_body_norm = _lp_sequence_body(existing_lp_section)
            existing_hash = hashlib.sha256(existing_body_norm.encode("utf-8")).hexdigest()

            stored_hash = None
            if os.path.isfile(hash_file):
                try:
                    with open(hash_file, "r", encoding="utf-8") as f:
                        stored_hash = f.read().strip() or None
                except Exception:
                    stored_hash = None

            if stored_hash is None or stored_hash == existing_hash:
                generated_body_norm = _lp_sequence_body(new_lp_match.group(0))
                new_hash = hashlib.sha256(generated_body_norm.encode("utf-8")).hexdigest()
                os.makedirs(cache_dir, exist_ok=True)
                try:
                    with open(hash_file, "w", encoding="utf-8") as f:
                        f.write(new_hash)
                except Exception:
                    pass
            else:
                new_body = new_body[:new_lp_match.start()] + existing_lp_section + "\n" + new_body[new_lp_match.end():]
                if final_fm:
                    if "lp_sequence_source:" in final_fm:
                        final_fm = re.sub(
                            r"lp_sequence_source:\s*\"?[a-zA-Z]+\"?",
                            'lp_sequence_source: "user"',
                            final_fm,
                        )
                    else:
                        final_fm = final_fm.rstrip()
                        if final_fm.endswith("---"):
                            final_fm = final_fm[:-3].rstrip() + '\nlp_sequence_source: "user"\n---'
                try:
                    if os.path.isfile(hash_file):
                        os.remove(hash_file)
                except Exception:
                    pass
        else:
            new_body = new_body[:new_lp_match.start()] + existing_lp_section + "\n" + new_body[new_lp_match.end():]

    final = final_fm + "\n\n" + new_body if final_fm else new_body
    with open(path, "w", encoding="utf-8") as f:
        f.write(final)


def _maybe_seed_lp_sequence_hash(readme_path: str, content: str, project: str) -> None:
    if not content.startswith("---"):
        return
    second_dash = content.find("---", 3)
    if second_dash == -1:
        return
    fm = content[:second_dash + 3]
    body = content[second_dash + 3:]
    fm_dict = _parse_frontmatter_dict(fm)
    if fm_dict.get("lp_sequence_source", "").strip().lower() != "auto":
        return
    lp_pattern = re.compile(r"(## LP 序列\s*\n)(.*?)(?=\n## |\Z)", re.DOTALL)
    m = lp_pattern.search(body)
    if not m:
        return
    body_norm = _lp_sequence_body(m.group(0))
    h = hashlib.sha256(body_norm.encode("utf-8")).hexdigest()
    cache_dir = os.path.join(project, "status", ".cache")
    os.makedirs(cache_dir, exist_ok=True)
    with open(os.path.join(cache_dir, "lp_sequence_hash.txt"), "w", encoding="utf-8") as f:
        f.write(h)
