"""Regenerate every file under views/ from status.yaml.

Views are read-only output. Each render overwrites them entirely.

Usage:
    python render_status.py --project <project_root>
"""
from __future__ import annotations

import argparse
import hashlib
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import _yaml_compat as yaml
import handoff as ho_helpers
import meta as meta_helpers
import re


HEADER = "<!-- AUTOGENERATED by tools/render_status.py — do not edit by hand. -->\n\n"


def _tldr(status: dict, view: str) -> str:
    """Return a short TL;DR block prepended to every view.

    The first 10 lines of any view should give an AI agent enough information
    to answer most questions without reading the rest of the file.
    """
    s = meta_helpers.compute_summary(status)
    hotspots = meta_helpers.compute_hotspots(status)
    lines = ["<!-- ANCHOR: tldr -->", "## TL;DR", ""]
    lines.append(
        f"- Artifacts: {s['artifacts_total']} total · "
        f"✅ {s['artifacts_ready']} ready · "
        f"🚫 {s['artifacts_blocked']} blocked · "
        f"🟡 {s['artifacts_needs_update']} needs_update"
    )
    lines.append(
        f"- Blockers open: {s['blockers_open']} · Gates failed: {s['gates_failed']}"
    )
    lines.append(
        f"- Handoffs: {s['handoffs_total']} total · "
        f"⚠️ {s['handoffs_stale']} stale · "
        f"❌ {s['handoffs_invalidated']} invalidated · "
        f"⏳ {s['handoffs_pending_consumers']} pending consumers"
    )
    if hotspots:
        lines.append("- **Hotspots**:")
        for h in hotspots:
            lines.append(f"  - {h}")
    lines.append(f"- This view scope: `{view}`. See `AGENTS.md` for the full index.")
    lines.append("")
    return "\n".join(lines) + "\n"


def write_view(project: str, name: str, body: str):
    path = os.path.join(project, "views", name)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(HEADER + body)


def write_root(project: str, name: str, body: str):
    """Write a file directly at the project root (used for AGENTS.md)."""
    path = os.path.join(project, name)
    with open(path, "w", encoding="utf-8") as f:
        f.write(body)


def render_status_report(status: dict) -> str:
    proj = status.get("project") or {}
    arts = status.get("artifacts") or []
    counts = {}
    for a in arts:
        counts[a.get("status", "?")] = counts.get(a.get("status", "?"), 0) + 1

    blockers = status.get("blockers") or []
    open_blockers = [b for b in blockers if b.get("status") == "open"]
    gates = status.get("gates") or []
    failed_gates = [g for g in gates if g.get("status") == "failed"]
    ready_lps = [a for a in arts if a.get("type") == "landing_prompt" and a.get("status") == "ready"]
    blocked_lps = [a for a in arts if a.get("type") == "landing_prompt" and a.get("status") == "blocked"]
    needs_update_tps = [a for a in arts if a.get("type") == "test_prompt" and a.get("status") == "needs_update"]
    events = status.get("change_events") or []
    recent = events[-5:][::-1]

    out = []
    out.append(f"# Status Report\n")
    out.append(f"- **Project**: {proj.get('name', 'unknown')}")
    out.append(f"- **Phase**: {proj.get('phase', '?')}")
    out.append(f"- **Version**: {proj.get('version', '?')}\n")
    out.append("<!-- ANCHOR: artifacts -->")
    out.append(f"## Artifacts ({len(arts)})\n")
    if counts:
        for k in sorted(counts):
            out.append(f"- `{k}`: {counts[k]}")
    else:
        out.append("_(none registered)_")
    out.append("")
    out.append("<!-- ANCHOR: blockers -->")
    out.append(f"## Open blockers ({len(open_blockers)})\n")
    if open_blockers:
        for b in open_blockers:
            out.append(f"- **{b['id']}** ({b.get('severity', '?')}): {b.get('title', '')}")
    else:
        out.append("_(none)_")
    out.append("")
    out.append("<!-- ANCHOR: gates -->")
    out.append(f"## Failed gates ({len(failed_gates)})\n")
    if failed_gates:
        for g in failed_gates:
            out.append(f"- **{g['id']}** {g.get('name', '')}")
    else:
        out.append("_(none)_")
    out.append("")
    out.append("<!-- ANCHOR: landing-prompts -->")
    out.append(f"## LandingPrompts: ready ({len(ready_lps)}) / blocked ({len(blocked_lps)})\n")
    for a in ready_lps:
        out.append(f"- ✅ ready: `{a['id']}` ({a.get('path', '')})")
    for a in blocked_lps:
        out.append(f"- 🚫 blocked: `{a['id']}` ({a.get('path', '')})")
    if not ready_lps and not blocked_lps:
        out.append("_(none)_")
    out.append("")
    out.append("<!-- ANCHOR: test-prompts -->")
    out.append(f"## TestPrompts needing update ({len(needs_update_tps)})\n")
    for a in needs_update_tps:
        out.append(f"- 🟡 `{a['id']}` ({a.get('path', '')})")
    if not needs_update_tps:
        out.append("_(none)_")
    out.append("")
    out.append("<!-- ANCHOR: recent-events -->")
    out.append(f"## Recent change events ({len(recent)} most recent)\n")
    for ce in recent:
        out.append(f"### {ce.get('id', '?')} — {ce.get('time', '?')}")
        out.append(f"- **Source**: {ce.get('source', '')}")
        out.append(f"- **Summary**: {ce.get('summary', '')}")
        for t in ce.get("transitions") or []:
            out.append(f"  - `{t.get('artifact')}`: {t.get('from')} → {t.get('to')} — {t.get('reason', '')}")
        out.append("")

    # Handoff summary
    hcs = status.get("handoff_contexts") or []
    stale = [h for h in hcs if h.get("status") == "stale"]
    invalid = [h for h in hcs if h.get("status") == "invalidated"]
    pending_consumers = 0
    for h in hcs:
        for ce in h.get("consumed_status") or []:
            if ce.get("status") == "pending":
                pending_consumers += 1
    out.append("<!-- ANCHOR: handoffs -->")
    out.append(f"## Handoffs ({len(hcs)})\n")
    out.append(f"- stale: {len(stale)}")
    out.append(f"- invalidated: {len(invalid)}")
    out.append(f"- pending consumers: {pending_consumers}")
    if stale:
        out.append("\nStale handoffs:")
        for h in stale:
            out.append(f"- `{h['id']}` (producer: `{h.get('producer', '?')}`, v{h.get('version', '?')})")
    if invalid:
        out.append("\nInvalidated handoffs:")
        for h in invalid:
            out.append(f"- `{h['id']}` (producer: `{h.get('producer', '?')}`)")
    out.append("")
    return "\n".join(out)


def render_blocker_view(status: dict) -> str:
    out = ["# Blocker View\n"]
    blockers = status.get("blockers") or []
    open_b = [b for b in blockers if b.get("status") == "open"]
    if not open_b:
        out.append("_(no open blockers)_")
        return "\n".join(out)
    # Sort by severity descending.
    sev_order = {"critical": 0, "high": 1, "medium": 2, "low": 3}
    open_b.sort(key=lambda b: sev_order.get(b.get("severity", "medium"), 4))
    for b in open_b:
        out.append(f"## {b['id']} — {b.get('title', '')}")
        out.append(f"- **Severity**: {b.get('severity', '?')}")
        srcs = b.get("source") or []
        out.append(f"- **Source**: {', '.join(srcs) if srcs else '_(unspecified)_'}")
        blocks = b.get("blocks") or []
        out.append(f"- **Blocks**: {', '.join(blocks) if blocks else '_(none)_'}")
        gates = b.get("resolution_required_for") or []
        out.append(f"- **Resolution required for**: {', '.join(gates) if gates else '_(none)_'}")
        out.append("")
    out.append("## Suggested resolution order\n")
    for i, b in enumerate(open_b, 1):
        out.append(f"{i}. **{b['id']}** ({b.get('severity', '?')}) — {b.get('title', '')}")
    return "\n".join(out)


def render_landing_checklist(status: dict) -> str:
    out = ["# Landing Prompt Checklist\n"]
    arts = status.get("artifacts") or []
    lps = [a for a in arts if a.get("type") == "landing_prompt"]
    arts_by_id = {a["id"]: a for a in arts}
    pcs_by_target: dict[str, list[dict]] = {}
    for pc in status.get("preconditions") or []:
        pcs_by_target.setdefault(pc.get("target", ""), []).append(pc)

    if not lps:
        out.append("_(no landing prompts registered)_")
        return "\n".join(out)

    for lp in lps:
        out.append(f"## {lp['id']} — status: `{lp.get('status', '?')}`")
        out.append(f"- **Path**: {lp.get('path', '')}")
        deps = lp.get("depends_on") or []
        out.append(f"- **Depends on**: {', '.join(deps) if deps else '_(none)_'}")
        # Identify TestPrompt dep
        tp_dep = next((d for d in deps if d.startswith("TestPrompt.")), None)
        if tp_dep:
            tp = arts_by_id.get(tp_dep)
            out.append(f"  - TestPrompt `{tp_dep}` status: `{tp.get('status', '?') if tp else 'unregistered'}`")
        plan_dep = next((d for d in deps if d.startswith("Plan.")), None)
        if plan_dep:
            pl = arts_by_id.get(plan_dep)
            out.append(f"  - Plan `{plan_dep}` status: `{pl.get('status', '?') if pl else 'unregistered'}`")
        pcs = pcs_by_target.get(lp["id"], [])
        out.append(f"- **Preconditions**: {len(pcs)}")
        all_pass = True
        for pc in pcs:
            mark = "✅" if pc.get("status") == "passing" else "❌"
            req_parts = []
            for r in (pc.get("requires") or []):
                if "handoff" in r:
                    if "in" in r:
                        req_parts.append(f"handoff {r['handoff']}.{r.get('field', 'status')} ∈ {r['in']}")
                    elif "min" in r:
                        req_parts.append(f"handoff {r['handoff']}.{r.get('field', 'version')} ≥ {r['min']}")
                    elif "equals" in r:
                        req_parts.append(f"handoff {r['handoff']}.{r.get('field', 'status')} = {r['equals']}")
                    else:
                        req_parts.append(f"handoff {r['handoff']}.{r.get('field', '?')}")
                else:
                    req_parts.append(f"{r.get('artifact')}.{r.get('field', 'status')}={r.get('equals')}")
            req_summary = ", ".join(req_parts)
            if pc.get("status") != "passing":
                all_pass = False
            out.append(f"  - {mark} {pc['id']}: {req_summary}")
        # Handoff consumption summary for this LP
        consumes = lp.get("consumes_handoffs") or []
        if consumes:
            out.append(f"- **Consumes handoffs**: {', '.join(consumes)}")
            for hc_id in consumes:
                hc = ho_helpers.get_handoff(status, hc_id)
                if not hc:
                    out.append(f"  - ❌ `{hc_id}` not registered")
                    all_pass = False
                    continue
                ce = ho_helpers.consumer_entry(hc, lp["id"]) or {}
                mark = "✅" if (ce.get("status") == "consumed" and ce.get("consumed_version") == hc.get("version")) else "🟡"
                out.append(f"  - {mark} `{hc_id}` v{hc.get('version', '?')} [{hc.get('status', '?')}] — consumer: {ce.get('status', 'pending')} v{ce.get('consumed_version')}")
        produces = lp.get("produces_handoffs") or []
        if produces:
            out.append(f"- **Produces handoffs**: {', '.join(produces)}")
        blocked_by = lp.get("blocked_by") or []
        if blocked_by:
            out.append(f"- **Blocked by**: {', '.join(blocked_by)}")
        executable = lp.get("status") == "ready" and all_pass and not blocked_by
        out.append(f"- **Executable**: {'✅ yes' if executable else '❌ no'}")
        if not executable and lp.get("status") != "ready":
            out.append(f"  - Reason: artifact status is `{lp.get('status', '?')}`, not `ready`.")
        if not all_pass:
            out.append(f"  - Reason: one or more preconditions failed (see above).")
        if blocked_by:
            out.append(f"  - Reason: blocked by {', '.join(blocked_by)}.")
        out.append("")
    return "\n".join(out)


def render_dep_graph(status: dict) -> str:
    out = ["# Dependency Graph\n", "```mermaid", "graph TD"]
    arts = status.get("artifacts") or []
    findings = status.get("research_findings") or []
    decisions = status.get("decisions") or []

    def node(nid: str, label: str | None = None) -> str:
        safe = nid.replace(".", "_").replace("-", "_")
        lbl = label or nid
        return f"    {safe}[\"{lbl}\"]"

    def edge(a: str, b: str) -> str:
        return f"    {a.replace('.', '_').replace('-', '_')} --> {b.replace('.', '_').replace('-', '_')}"

    for rf in findings:
        out.append(node(rf["id"], f"{rf['id']} {rf.get('title', '')}"))
    for d in decisions:
        out.append(node(d["id"], f"{d['id']} {d.get('title', '')}"))
    for a in arts:
        out.append(node(a["id"], f"{a['id']}\\n[{a.get('status', '?')}]"))

    # Edges from research affects/invalidates.
    for rf in findings:
        for tid in rf.get("affects") or []:
            out.append(edge(rf["id"], tid))
    # Edges from decision based_on / affects.
    for d in decisions:
        for src in d.get("based_on") or []:
            out.append(edge(src, d["id"]))
        for tid in d.get("affects") or []:
            out.append(edge(d["id"], tid))
    # Edges from artifact depends_on / affected_by.
    for a in arts:
        for dep in a.get("depends_on") or []:
            out.append(edge(dep, a["id"]))
        for src in a.get("affected_by") or []:
            out.append(edge(src, a["id"]))

    out.append("```")
    return "\n".join(out)


def render_change_impact(status: dict) -> str:
    out = ["# Change Impact Report\n"]
    events = status.get("change_events") or []
    if not events:
        out.append("_(no change events recorded yet)_")
        return "\n".join(out)
    ce = events[-1]
    out.append(f"## Most recent event: {ce.get('id', '?')}")
    out.append(f"- **Time**: {ce.get('time', '?')}")
    out.append(f"- **Source**: {ce.get('source', '')}")
    out.append(f"- **Event type**: {ce.get('event_type', '')}")
    out.append(f"- **Summary**: {ce.get('summary', '')}")
    out.append("")
    out.append(f"## Affected artifacts ({len(ce.get('affected') or [])})")
    for aid in ce.get("affected") or []:
        out.append(f"- `{aid}`")
    out.append("")
    out.append("## State transitions")
    out.append("| Artifact | From | To | Reason |")
    out.append("| --- | --- | --- | --- |")
    for t in ce.get("transitions") or []:
        out.append(f"| `{t.get('artifact')}` | {t.get('from')} | {t.get('to')} | {t.get('reason', '')} |")
    out.append("")
    out.append("## Suggested next actions")
    out.append("1. Review each transitioned artifact for content corrections.")
    out.append("2. Re-check preconditions for any LandingPrompt now in `blocked` or `needs_update`.")
    out.append("3. If a TestPrompt is now `needs_update`, update it before its LandingPrompt is run.")
    out.append("")
    # Handoff issue summary
    issues = analyze_handoff_issues(status)
    if issues:
        out.append(f"## Handoff issues ({len(issues)})")
        for line in issues:
            out.append(f"- {line}")
    return "\n".join(out)


def analyze_handoff_issues(status: dict) -> list:
    """Return a list of human-readable strings describing handoff problems."""
    out = []
    arts_by_id = {a.get("id"): a for a in status.get("artifacts") or []}
    for hc in status.get("handoff_contexts") or []:
        s = hc.get("status")
        hc_id = hc.get("id")
        if s == "stale":
            out.append(f"`{hc_id}` is stale (producer changed; downstream consumers may be affected)")
        elif s == "invalidated":
            out.append(f"`{hc_id}` is invalidated; consumers must reconsider their plan")
        elif s == "deprecated":
            out.append(f"`{hc_id}` is deprecated; new artifacts should not consume it")
        # Version-drift consumers
        cur_v = hc.get("version")
        for ce in hc.get("consumed_status") or []:
            cv = ce.get("consumed_version")
            if isinstance(cv, int) and isinstance(cur_v, int) and cv < cur_v:
                out.append(f"`{hc_id}` consumer `{ce.get('consumer')}` absorbed v{cv} but current is v{cur_v}")
            if ce.get("status") == "rejected":
                reason = ce.get("reason", "")
                out.append(f"`{hc_id}` rejected by `{ce.get('consumer')}`: {reason}")
        # Pending consumers when handoff is available — informational only.
    return out


def render_handoff_view(status: dict) -> str:
    out = ["# Handoff View\n"]
    hcs = status.get("handoff_contexts") or []
    if not hcs:
        out.append("_(no handoff contexts registered)_")
        return "\n".join(out)

    out.append("## Summary\n")
    out.append("| Handoff | Producer | Status | Version | Consumers | Issues |")
    out.append("| --- | --- | --- | --- | --- | --- |")
    for hc in hcs:
        consumers = hc.get("consumed_by") or []
        issues = []
        if hc.get("status") in ho_helpers.BLOCKING_HANDOFF_STATUSES:
            issues.append(hc.get("status"))
        cur_v = hc.get("version")
        for ce in hc.get("consumed_status") or []:
            cv = ce.get("consumed_version")
            if isinstance(cv, int) and isinstance(cur_v, int) and cv < cur_v:
                issues.append(f"{ce.get('consumer')} used v{cv}")
            if ce.get("status") == "rejected":
                issues.append(f"{ce.get('consumer')} rejected")
            if ce.get("status") == "pending":
                issues.append(f"{ce.get('consumer')} pending")
            if ce.get("status") == "stale":
                issues.append(f"{ce.get('consumer')} stale")
        issue_str = "; ".join(issues) if issues else "_(ok)_"
        out.append(f"| `{hc['id']}` | `{hc.get('producer', '?')}` | {hc.get('status', '?')} | {cur_v} | {', '.join(consumers) if consumers else '_(none)_'} | {issue_str} |")
    out.append("")

    for hc in hcs:
        out.append(f"## {hc['id']} — {hc.get('title', '')}\n")
        out.append(f"- **Producer**: `{hc.get('producer', '?')}` ({hc.get('producer_type', '?')})")
        produced_from = hc.get("produced_from") or []
        out.append(f"- **Produced from**: {', '.join(produced_from) if produced_from else '_(none)_'}")
        out.append(f"- **Status**: `{hc.get('status', '?')}`")
        out.append(f"- **Version**: {hc.get('version', '?')}")
        out.append(f"- **Last verified**: {hc.get('last_verified', '_(never)_')}")

        facts = hc.get("facts") or []
        out.append(f"\n### Facts ({len(facts)})\n")
        for f in facts:
            if isinstance(f, dict):
                out.append(f"- **{f.get('id', '?')}**: {f.get('statement', '')} (source: `{f.get('source', '?')}`, confidence: {f.get('confidence', '?')})")
            else:
                # Legacy format: plain string
                out.append(f"- {f}")
        if not facts:
            out.append("_(none)_")

        results = hc.get("results") or []
        out.append(f"\n### Results ({len(results)})\n")
        for r in results:
            out.append(f"- **{r.get('id', '?')}** ({r.get('type', '?')}): `{r.get('path', '?')}` — {r.get('summary', '')}")
        if not results:
            out.append("_(none)_")

        constraints = hc.get("constraints") or []
        out.append(f"\n### Constraints ({len(constraints)})\n")
        for c in constraints:
            if isinstance(c, dict):
                out.append(f"- **{c.get('id', '?')}**: {c.get('statement', '')} (source: `{c.get('source', '?')}`)")
            else:
                # Legacy format: plain string
                out.append(f"- {c}")
        if not constraints:
            out.append("_(none)_")

        cs = hc.get("consumed_status") or []
        out.append(f"\n### Consumption ({len(cs)})\n")
        out.append("| Consumer | Status | Consumed Version | When |")
        out.append("| --- | --- | --- | --- |")
        for ce in cs:
            extra = ""
            if ce.get("status") == "rejected" and ce.get("reason"):
                extra = f" _(reason: {ce.get('reason')})_"
            out.append(f"| `{ce.get('consumer')}` | {ce.get('status', '?')}{extra} | {ce.get('consumed_version')} | {ce.get('consumed_at', '_(never)_')} |")
        out.append("")
    return "\n".join(out)


def render_prompt_chain_view(status: dict) -> str:
    out = ["# Prompt Chain View\n"]
    arts = status.get("artifacts") or []
    arts_by_id = {a["id"]: a for a in arts}
    hcs = status.get("handoff_contexts") or []
    lps = [a for a in arts if a.get("type") == "landing_prompt"]
    tps = [a for a in arts if a.get("type") == "test_prompt"]

    out.append("```mermaid")
    out.append("graph TD")

    def safe(s: str) -> str:
        return (s or "").replace(".", "_").replace("-", "_").replace(":", "_")

    for lp in lps:
        out.append(f"    {safe(lp['id'])}[\"LP {lp['id']}\\n[{lp.get('status', '?')}]\"]")
    for tp in tps:
        out.append(f"    {safe(tp['id'])}[\"TP {tp['id']}\\n[{tp.get('status', '?')}]\"]")
    for hc in hcs:
        out.append(f"    {safe(hc['id'])}((HC {hc['id']}\\n{hc.get('status', '?')} v{hc.get('version', '?')}))")

    # Edges: producer -> HC -> consumer
    for hc in hcs:
        producer = hc.get("producer")
        if producer and producer in arts_by_id:
            out.append(f"    {safe(producer)} --> {safe(hc['id'])}")
        for consumer in hc.get("consumed_by") or []:
            if consumer in arts_by_id:
                out.append(f"    {safe(hc['id'])} --> {safe(consumer)}")
    out.append("```")
    out.append("")

    # Breakpoints
    breakpoints = []
    for hc in hcs:
        if hc.get("status") in ho_helpers.BLOCKING_HANDOFF_STATUSES:
            breakpoints.append(f"`{hc['id']}` is {hc.get('status')}; blocks {', '.join(hc.get('consumed_by') or []) or '(no consumers)'}")
        for ce in hc.get("consumed_status") or []:
            if ce.get("status") == "rejected":
                breakpoints.append(f"`{hc['id']}` rejected by `{ce.get('consumer')}`")
            cv = ce.get("consumed_version")
            cur_v = hc.get("version")
            if isinstance(cv, int) and isinstance(cur_v, int) and cv < cur_v:
                breakpoints.append(f"`{hc['id']}` consumer `{ce.get('consumer')}` on v{cv} (current v{cur_v})")

    out.append(f"## Breakpoints ({len(breakpoints)})\n")
    if breakpoints:
        for b in breakpoints:
            out.append(f"- {b}")
    else:
        out.append("_(none)_")
    out.append("")

    # Suggested next prompt: first ready LP whose handoff inputs are all ok.
    suggested = None
    for lp in lps:
        if lp.get("status") != "ready":
            continue
        ok = True
        for hc_id in lp.get("consumes_handoffs") or []:
            hc = ho_helpers.get_handoff(status, hc_id)
            if not hc or hc.get("status") in ho_helpers.BLOCKING_HANDOFF_STATUSES:
                ok = False
                break
        if ok:
            suggested = lp
            break
    out.append("## Suggested next prompt\n")
    if suggested:
        out.append(f"- ✅ `{suggested['id']}` ({suggested.get('path', '')})")
    else:
        out.append("_(no LandingPrompt is currently ready with all handoffs available)_")
    out.append("")

    # Non-executable prompts with reasons
    out.append("## Non-executable LandingPrompts\n")
    any_blocked = False
    for lp in lps:
        if lp.get("status") == "ready":
            continue
        any_blocked = True
        reasons = [f"status is `{lp.get('status', '?')}`"]
        for hc_id in lp.get("consumes_handoffs") or []:
            hc = ho_helpers.get_handoff(status, hc_id)
            if not hc:
                reasons.append(f"handoff `{hc_id}` not registered")
            elif hc.get("status") in ho_helpers.BLOCKING_HANDOFF_STATUSES:
                reasons.append(f"handoff `{hc_id}` is {hc.get('status')}")
        out.append(f"- `{lp['id']}` — {'; '.join(reasons)}")
    if not any_blocked:
        out.append("_(none)_")
    return "\n".join(out)



def _build_dependency_graph_text(status: dict) -> str:
    """Build a simple text dependency graph for README."""
    arts = status.get("artifacts") or []
    lines = []
    for a in arts:
        for dep in a.get("depends_on") or []:
            lines.append(f"{dep} <- {a['id']}")
    if not lines:
        return "(无依赖关系)"
    return "\n".join(lines)


def _topological_sort_lps(artifacts: list) -> list:
    """Topologically sort LP artifacts by depends_on. Falls back to ID order on cycles."""
    lps = [a for a in artifacts if a.get("type") == "landing_prompt"]
    if not lps:
        return []
    # Build adjacency
    ids = {a["id"] for a in lps}
    graph = {a["id"]: [] for a in lps}
    in_degree = {a["id"]: 0 for a in lps}
    for a in lps:
        for dep in a.get("depends_on") or []:
            if dep in ids:
                graph[dep].append(a["id"])
                in_degree[a["id"]] += 1
    # Kahn's algorithm
    queue = sorted([n for n, d in in_degree.items() if d == 0])
    result = []
    while queue:
        node = queue.pop(0)
        result.append(node)
        for neighbor in sorted(graph.get(node, [])):
            in_degree[neighbor] -= 1
            if in_degree[neighbor] == 0:
                queue.append(neighbor)
    # Cycle detection: if not all nodes visited, append remaining by ID
    if len(result) < len(lps):
        remaining = sorted(ids - set(result))
        result.extend(remaining)
    return result


def render_project_readme(status: dict, project: str) -> str:
    """Generate PST project root README.md."""
    meta = status.get("meta") or {}
    proj = status.get("project") or {}
    proj_name = proj.get("name") or meta.get("project_name", "Unknown Project")
    arts = status.get("artifacts") or []
    findings = status.get("research_findings") or []
    decisions = status.get("decisions") or []
    hcs = status.get("handoff_contexts") or []
    blockers = status.get("blockers") or []

    lines = []
    lines.append(f"# {proj_name} — Project State Overview")
    lines.append("")
    lines.append("> Auto-generated by project-state-tracker. Do not hand-edit.")
    lines.append(f"> Last updated: {meta.get('last_run', 'unknown')}")
    lines.append("")

    # Directory structure
    lines.append("## 目录结构")
    lines.append("")
    dir_counts = {}
    for subdir in ["research", "decisions", "plan", os.path.join("prompts", "landing"),
                   os.path.join("prompts", "test"), "status", "views", "tools"]:
        full = os.path.join(project, subdir)
        if os.path.isdir(full):
            count = sum(1 for f in os.listdir(full)
                       if os.path.isfile(os.path.join(full, f)) and f not in (".gitkeep", ".gitignore"))
            dir_counts[subdir] = count
    for d, desc in [("research", "调研事实与证据"), ("decisions", "基于调研的决策"),
                    ("plan", "执行计划与设计"), (os.path.join("prompts", "landing"), "实施 Prompt"),
                    (os.path.join("prompts", "test"), "验证 Prompt")]:
        if d in dir_counts:
            lines.append(f"{d.ljust(20)}— {desc} ({dir_counts[d]} files)")
    lines.append("status/status.yaml  — 状态单一真相源")
    if "views" in dir_counts:
        lines.append("views/              — 只读派生视图")
    if "tools" in dir_counts:
        lines.append("tools/              — Python 状态管理脚本")
    lines.append("")

    # Artifact table
    all_arts = []
    for rf in findings:
        all_arts.append((rf.get("id", "?"), "research", rf.get("status", "?"), rf.get("path", "")))
    for d in decisions:
        all_arts.append((d.get("id", "?"), "decision", d.get("status", "?"), d.get("path", "")))
    for a in arts:
        all_arts.append((a.get("id", "?"), a.get("type", "?"), a.get("status", "?"), a.get("path", "")))
    all_arts.sort(key=lambda x: x[0])

    lines.append("## Artifact 状态总览")
    lines.append("")
    if all_arts:
        lines.append("| ID | Type | Status | Path |")
        lines.append("|----|------|--------|------|")
        for aid, atype, astatus, apath in all_arts:
            lines.append(f"| {aid} | {atype} | {astatus} | {apath} |")
    else:
        lines.append("无已注册 artifact")
    lines.append("")

    # Dependency graph
    lines.append("## 依赖关系图")
    lines.append("")
    lines.append(_build_dependency_graph_text(status))
    lines.append("")

    # Handoff
    lines.append("## Handoff 上下文")
    lines.append("")
    if hcs:
        lines.append("| HC | Producer | Status | Version | Consumers |")
        lines.append("|----|----------|--------|---------|-----------|")
        for hc in hcs:
            consumers = ", ".join(hc.get("consumed_by") or []) or "(none)"
            lines.append(f"| {hc.get('id')} | {hc.get('producer', '?')} | {hc.get('status', '?')} | {hc.get('version', '?')} | {consumers} |")
    else:
        lines.append("(无活跃 handoff)")
    lines.append("")

    # Blockers
    lines.append("## Blockers")
    lines.append("")
    open_blockers = [b for b in blockers if b.get("status") == "open"]
    if open_blockers:
        for b in open_blockers:
            lines.append(f"- **{b.get('id')}** ({b.get('severity', '?')}): {b.get('title', '')}")
    else:
        lines.append("(无阻塞项)")
    lines.append("")

    # Quick nav
    lines.append("## 快速导航")
    lines.append("")
    lines.append("- 完整状态数据: status/status.yaml")
    lines.append("- 变更日志: views/change_impact_report.md")
    lines.append("- Prompt 执行链: views/prompt_chain_view.md")
    lines.append("- Handoff 详情: views/handoff_view.md")
    lines.append("")
    return "\n".join(lines)


def render_landing_readme(status: dict, project: str) -> str:
    """Generate prompts/landing/README.md body (ELP-compatible).
    
    Front-matter is preserved if the file already exists with user-edited front-matter.
    The ## LP 序列 section is also preserved if it already exists (user-authored takes priority).
    """
    meta = status.get("meta") or {}
    proj = status.get("project") or {}
    proj_name = proj.get("name") or meta.get("project_name", "Unknown Project")
    arts = status.get("artifacts") or []
    hcs = status.get("handoff_contexts") or []

    # Generate front-matter from meta
    source_root = meta.get("source_root", "<\u672a\u914d\u7f6e>")
    scope = meta.get("scope") or []
    pst_root_val = meta.get("pst_root", "<\u672a\u914d\u7f6e>")

    fm_lines = ["---"]
    fm_lines.append(f'source_root: "{source_root}"')
    if scope:
        fm_lines.append("scope:")
        for s in scope:
            fm_lines.append(f'  - "{s}"')
    if pst_root_val and "\u672a\u914d\u7f6e" not in pst_root_val:
        fm_lines.append(f'pst_root: "{pst_root_val}"')
    fm_lines.append("---")
    new_frontmatter = "\n".join(fm_lines)

    # Body
    body_lines = []
    body_lines.append(f"# {proj_name} LandingPrompt")
    body_lines.append("")
    body_lines.append("> Auto-generated body by project-state-tracker. Front-matter and LP \u5e8f\u5217 preserved if pre-existing.")
    body_lines.append(f"> Last updated: {meta.get('last_run', 'unknown')}")
    body_lines.append("")

    # LP 序列 — generated from topological sort
    lp_order = _topological_sort_lps(arts)
    body_lines.append("## LP \u5e8f\u5217")
    body_lines.append("")
    if lp_order:
        body_lines.append(" -> ".join(lp_order))
    else:
        body_lines.append("\u5c1a\u65e0\u5df2\u6ce8\u518c\u7684 Landing Prompt")
    body_lines.append("")

    # Coding Standards
    coding_standards = meta.get("coding_standards")
    if coding_standards:
        body_lines.append("## Coding Standards")
        body_lines.append("")
        body_lines.append(coding_standards)
        body_lines.append("")

    # LP status table
    lps = [a for a in arts if a.get("type") == "landing_prompt"]
    body_lines.append("## \u5f53\u524d LP \u72b6\u6001")
    body_lines.append("")
    if lps:
        body_lines.append("| ID | Status | Depends On | Produces HC |")
        body_lines.append("|----|--------|------------|-------------|")
        for lp in lps:
            deps = ", ".join(lp.get("depends_on") or []) or "(none)"
            produces = ", ".join(lp.get("produces_handoffs") or []) or "(none)"
            body_lines.append(f"| {lp.get('id')} | {lp.get('status', '?')} | {deps} | {produces} |")
    else:
        body_lines.append("\u5c1a\u65e0\u5df2\u6ce8\u518c\u7684 Landing Prompt")
    body_lines.append("")

    # Handoff summary
    lp_ids = {a.get("id") for a in lps}
    relevant_hcs = [hc for hc in hcs if hc.get("producer") in lp_ids or
                    any(c in lp_ids for c in (hc.get("consumed_by") or []))]
    body_lines.append("## Handoff \u4e0a\u4e0b\u6587\u6458\u8981")
    body_lines.append("")
    if relevant_hcs:
        body_lines.append("| HC | Facts | Constraints | Consumed By |")
        body_lines.append("|----|-------|-------------|-------------|")
        for hc in relevant_hcs:
            facts = hc.get("facts") or []
            constraints = hc.get("constraints") or []
            fact_strs = []
            for f in facts:
                if isinstance(f, dict):
                    fact_strs.append(f.get("statement", str(f.get("id", "?"))))
                else:
                    fact_strs.append(str(f))
            constraint_strs = []
            for c in constraints:
                if isinstance(c, dict):
                    constraint_strs.append(c.get("statement", str(c.get("id", "?"))))
                else:
                    constraint_strs.append(str(c))
            facts_summary = "; ".join(fact_strs[:3]) if fact_strs else "(none)"
            constraints_summary = "; ".join(constraint_strs[:3]) if constraint_strs else "(none)"
            consumers = ", ".join(hc.get("consumed_by") or []) or "(none)"
            body_lines.append(f"| {hc.get('id')} | {facts_summary} | {constraints_summary} | {consumers} |")
    else:
        body_lines.append("(\u65e0\u6d3b\u8dc3 handoff)")
    body_lines.append("")

    new_body = "\n".join(body_lines)
    return new_frontmatter + "\n\n" + new_body


def _parse_frontmatter_dict(fm_text: str) -> dict:
    """Tiny YAML-ish front-matter parser limited to `key: "value"` and `key: value`.

    Used only to read `lp_sequence_source`. Avoids pulling a YAML dep just for this.
    Returns an empty dict on parse failure (caller will fall back to "user").
    """
    out = {}
    if not fm_text:
        return out
    lines = fm_text.strip().splitlines()
    # strip leading/trailing --- fence if present
    if lines and lines[0].strip() == "---":
        lines = lines[1:]
    if lines and lines[-1].strip() == "---":
        lines = lines[:-1]
    for raw in lines:
        line = raw.rstrip()
        if not line or line.lstrip().startswith("#") or ":" not in line:
            continue
        key, _, value = line.partition(":")
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        if key and value:
            out[key] = value
    return out


def _lp_sequence_body(section_text: str) -> str:
    """Normalize a ## LP 序列 section to the body lines after the heading."""
    if not section_text:
        return ""
    lines = section_text.splitlines()
    # drop the heading line
    if lines and lines[0].lstrip().startswith("## "):
        lines = lines[1:]
    return "\n".join(line.rstrip() for line in lines).strip()


def write_landing_readme_with_preservation(path: str, new_content: str, status: dict, project: str = None):
    """Write landing README preserving user front-matter and user-authored LP sequence.

    Preservation rules (G1 fix: lp_sequence_source-driven, hash-anchored):
    1. If file does not exist -> write new_content as-is.
    2. If front-matter has `lp_sequence_source: "auto"`:
       - Read `<project>/status/.cache/lp_sequence_hash.txt` (the last-known-auto body hash).
       - Compute sha256 of the CURRENT on-disk LP sequence body.
       - If hash file missing OR matches stored -> treat as agent-owned: regenerate from
         `new_content` and persist the new body's sha256 to the hash file (establishes/refreshes
         baseline so the next run can detect human edits). Keep front-matter as-is.
       - If hash differs (human edited the body since last auto-write) -> flip front-matter
         `lp_sequence_source` to "user", preserve the existing LP sequence section verbatim,
         and clear the hash file (no longer authoritative).
    3. If front-matter has `lp_sequence_source: "user"` OR the flag is absent (fail-safe):
       - Preserve existing LP sequence section verbatim if it exists.
    4. Front-matter (other keys) is always preserved if the existing file has one.
    """
    if not os.path.isfile(path):
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w", encoding="utf-8") as f:
            f.write(new_content)
        # On first write, if new_content carries an LP sequence section AND front-matter
        # marks it auto, seed the baseline hash so subsequent renders can detect edits.
        if project:
            try:
                _maybe_seed_lp_sequence_hash(path, new_content, project)
            except Exception:
                pass
        return

    existing = ""
    with open(path, "r", encoding="utf-8") as f:
        existing = f.read()

    # Extract existing front-matter
    existing_fm = ""
    existing_body = existing
    if existing.startswith("---"):
        second_dash = existing.find("---", 3)
        if second_dash != -1:
            existing_fm = existing[:second_dash + 3]
            existing_body = existing[second_dash + 3:].lstrip("\n")

    # Extract existing LP sequence section (## LP 序列)
    existing_lp_section = None
    lp_pattern = re.compile(r"(## LP \u5e8f\u5217\s*\n)(.*?)(?=\n## |\Z)", re.DOTALL)
    lp_match = lp_pattern.search(existing_body)
    if lp_match:
        existing_lp_section = lp_match.group(0).strip()

    # Parse new content into front-matter and body
    new_fm = ""
    new_body = new_content
    if new_content.startswith("---"):
        second_dash = new_content.find("---", 3)
        if second_dash != -1:
            new_fm = new_content[:second_dash + 3]
            new_body = new_content[second_dash + 3:].lstrip("\n")

    # G1: lp_sequence_source-aware preservation
    fm_dict = _parse_frontmatter_dict(existing_fm)
    # Fail-safe default: absent flag means "user" (never silently overwrite).
    lp_source = fm_dict.get("lp_sequence_source", "user").strip().lower()

    final_fm = existing_fm if existing_fm else new_fm
    new_lp_match = lp_pattern.search(new_body)

    if existing_lp_section and new_lp_match:
        if lp_source == "auto" and project:
            cache_dir = os.path.join(project, "status", ".cache")
            hash_file = os.path.join(cache_dir, "lp_sequence_hash.txt")
            existing_body_norm = _lp_sequence_body(existing_lp_section)
            existing_hash = hashlib.sha256(existing_body_norm.encode("utf-8")).hexdigest()

            stored_hash = None
            if os.path.isfile(hash_file):
                try:
                    with open(hash_file, "r", encoding="utf-8") as f:
                        stored_hash = f.read().strip() or None
                except Exception:
                    stored_hash = None

            if stored_hash is None or stored_hash == existing_hash:
                # Agent-owned: regenerate and refresh baseline.
                generated_body_norm = _lp_sequence_body(new_lp_match.group(0))
                new_hash = hashlib.sha256(generated_body_norm.encode("utf-8")).hexdigest()
                os.makedirs(cache_dir, exist_ok=True)
                try:
                    with open(hash_file, "w", encoding="utf-8") as f:
                        f.write(new_hash)
                except Exception:
                    pass
                # Leave new_body as-is (use the freshly generated LP section).
            else:
                # Human edited the body since last auto-write: flip flag, preserve content.
                new_body = new_body[:new_lp_match.start()] + existing_lp_section + "\n" + new_body[new_lp_match.end():]
                if final_fm:
                    if "lp_sequence_source:" in final_fm:
                        final_fm = re.sub(
                            r"lp_sequence_source:\s*\"?[a-zA-Z]+\"?",
                            'lp_sequence_source: "user"',
                            final_fm,
                        )
                    else:
                        final_fm = final_fm.rstrip()
                        if final_fm.endswith("---"):
                            final_fm = final_fm[:-3].rstrip() + '\nlp_sequence_source: "user"\n---'
                # Clear baseline — no longer authoritative.
                try:
                    if os.path.isfile(hash_file):
                        os.remove(hash_file)
                except Exception:
                    pass
        else:
            # lp_source == "user" (explicit or fail-safe) — preserve verbatim regardless of diff.
            new_body = new_body[:new_lp_match.start()] + existing_lp_section + "\n" + new_body[new_lp_match.end():]

    final = final_fm + "\n\n" + new_body if final_fm else new_body
    with open(path, "w", encoding="utf-8") as f:
        f.write(final)


def _maybe_seed_lp_sequence_hash(readme_path: str, content: str, project: str) -> None:
    """On first-write, if front-matter declares auto and an LP section exists,
    persist its sha256 as the baseline for future edit detection."""
    if not content.startswith("---"):
        return
    second_dash = content.find("---", 3)
    if second_dash == -1:
        return
    fm = content[:second_dash + 3]
    body = content[second_dash + 3:]
    fm_dict = _parse_frontmatter_dict(fm)
    if fm_dict.get("lp_sequence_source", "").strip().lower() != "auto":
        return
    lp_pattern = re.compile(r"(## LP \u5e8f\u5217\s*\n)(.*?)(?=\n## |\Z)", re.DOTALL)
    m = lp_pattern.search(body)
    if not m:
        return
    body_norm = _lp_sequence_body(m.group(0))
    h = hashlib.sha256(body_norm.encode("utf-8")).hexdigest()
    cache_dir = os.path.join(project, "status", ".cache")
    os.makedirs(cache_dir, exist_ok=True)
    with open(os.path.join(cache_dir, "lp_sequence_hash.txt"), "w", encoding="utf-8") as f:
        f.write(h)



def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--project", default=".")
    args = ap.parse_args()
    project = os.path.abspath(args.project)

    status_path = os.path.join(project, "status", "status.yaml")
    if not os.path.isfile(status_path):
        print("[render_status] FAIL: status.yaml not found", file=sys.stderr)
        sys.exit(2)
    with open(status_path, "r", encoding="utf-8") as f:
        status = yaml.load(f.read()) or {}

    # Refresh meta block so AGENTS.md and view TL;DRs reflect current state.
    # We do NOT write status.yaml back from the renderer — apply_changes owns writes.
    # We compute meta in-memory only for read consumers.
    meta_helpers.refresh_meta(status)

    def _v(body: str, view: str) -> str:
        return _tldr(status, view) + body

    write_view(project, "status_report.md", _v(render_status_report(status), "views/status_report.md"))
    write_view(project, "blocker_view.md", _v(render_blocker_view(status), "views/blocker_view.md"))
    write_view(project, "landing_prompt_checklist.md", _v(render_landing_checklist(status), "views/landing_prompt_checklist.md"))
    write_view(project, "dependency_graph.md", _v(render_dep_graph(status), "views/dependency_graph.md"))
    write_view(project, "change_impact_report.md", _v(render_change_impact(status), "views/change_impact_report.md"))
    write_view(project, "handoff_view.md", _v(render_handoff_view(status), "views/handoff_view.md"))
    write_view(project, "prompt_chain_view.md", _v(render_prompt_chain_view(status), "views/prompt_chain_view.md"))
    write_root(project, "AGENTS.md", meta_helpers.render_agents_md(status))
    # README rendering
    readme_content = render_project_readme(status, project)
    readme_path = os.path.join(project, "README.md")
    with open(readme_path, "w", encoding="utf-8") as f:
        f.write(readme_content)
    print(f"  Rendered: {readme_path}")

    landing_dir = os.path.join(project, "prompts", "landing")
    os.makedirs(landing_dir, exist_ok=True)
    landing_readme_content = render_landing_readme(status, project)
    landing_readme_path = os.path.join(landing_dir, "README.md")
    write_landing_readme_with_preservation(landing_readme_path, landing_readme_content, status, project)
    print(f"  Rendered: {landing_readme_path}")

    print("[render_status] regenerated 7 views + AGENTS.md + 2 READMEs")


if __name__ == "__main__":
    main()
